# Generated by Django 3.1.7 on 2021-03-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_parent_childage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
            options={
                'ordering': ['-age'],
            },
        ),
        migrations.RemoveField(
            model_name='parent',
            name='childage',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='childname',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='date',
        ),
    ]
