# Generated by Django 3.1.7 on 2021-03-24 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_parent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
    ]
