# Generated by Django 3.1.7 on 2021-03-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_parent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
