# Generated by Django 3.1.7 on 2021-03-24 04:04

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210324_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='parent',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number', max_length=31),
        ),
    ]
