# Generated by Django 3.1.7 on 2021-04-19 04:51

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210324_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('child_name', models.CharField(max_length=100)),
                ('week_number', models.IntegerField()),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number', max_length=31)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
