# Generated by Django 3.1.7 on 2021-04-27 16:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210427_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summer',
            name='week_number',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8'), ('9', 'Week 9'), ('10', 'Week 10'), ('11', 'Week 11')], default=1, max_length=23),
        ),
    ]
