# Generated by Django 3.1.7 on 2021-04-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210427_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='summer',
            name='date',
            field=models.DateField(default=1, verbose_name='Summer Dates'),
            preserve_default=False,
        ),
    ]
