# Generated by Django 3.1.7 on 2021-05-09 03:51

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210428_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('child_name', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
